// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package db_instance_read_replica

import (
	"context"

	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	ackerr "github.com/aws/aws-controllers-k8s/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/rds"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws/aws-controllers-k8s/services/rds/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = &svcsdk.RDS{}
	_ = &svcapitypes.DBInstanceReadReplica{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// TODO(jaypipes): Map out the ReadMany codepath

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()
	return &resource{ko}, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateDBInstanceReadReplicaWithContext(ctx, input)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	ko.Status.AllocatedStorage = resp.DBInstance.AllocatedStorage
	f1 := []*svcapitypes.DBInstanceRole{}
	for _, f1iter := range resp.DBInstance.AssociatedRoles {
		f1elem := &svcapitypes.DBInstanceRole{}
		f1elem.FeatureName = f1iter.FeatureName
		f1elem.RoleARN = f1iter.RoleArn
		f1elem.Status = f1iter.Status
		f1 = append(f1, f1elem)
	}
	ko.Status.AssociatedRoles = f1
	ko.Status.BackupRetentionPeriod = resp.DBInstance.BackupRetentionPeriod
	ko.Status.CACertificateIdentifier = resp.DBInstance.CACertificateIdentifier
	ko.Status.CharacterSetName = resp.DBInstance.CharacterSetName
	ko.Status.DBClusterIdentifier = resp.DBInstance.DBClusterIdentifier
	ko.Status.DBInstanceARN = resp.DBInstance.DBInstanceArn
	ko.Status.DBInstanceStatus = resp.DBInstance.DBInstanceStatus
	ko.Status.DBName = resp.DBInstance.DBName
	f14 := []*svcapitypes.DBParameterGroupStatus_SDK{}
	for _, f14iter := range resp.DBInstance.DBParameterGroups {
		f14elem := &svcapitypes.DBParameterGroupStatus_SDK{}
		f14elem.DBParameterGroupName = f14iter.DBParameterGroupName
		f14elem.ParameterApplyStatus = f14iter.ParameterApplyStatus
		f14 = append(f14, f14elem)
	}
	ko.Status.DBParameterGroups = f14
	f15 := []*svcapitypes.DBSecurityGroupMembership{}
	for _, f15iter := range resp.DBInstance.DBSecurityGroups {
		f15elem := &svcapitypes.DBSecurityGroupMembership{}
		f15elem.DBSecurityGroupName = f15iter.DBSecurityGroupName
		f15elem.Status = f15iter.Status
		f15 = append(f15, f15elem)
	}
	ko.Status.DBSecurityGroups = f15
	f16 := &svcapitypes.DBSubnetGroup_SDK{}
	f16.DBSubnetGroupARN = resp.DBInstance.DBSubnetGroup.DBSubnetGroupArn
	f16.DBSubnetGroupDescription = resp.DBInstance.DBSubnetGroup.DBSubnetGroupDescription
	f16.DBSubnetGroupName = resp.DBInstance.DBSubnetGroup.DBSubnetGroupName
	f16.SubnetGroupStatus = resp.DBInstance.DBSubnetGroup.SubnetGroupStatus
	f16f4 := []*svcapitypes.Subnet{}
	for _, f16f4iter := range resp.DBInstance.DBSubnetGroup.Subnets {
		f16f4elem := &svcapitypes.Subnet{}
		f16f4elemf0 := &svcapitypes.AvailabilityZone{}
		f16f4elemf0.Name = f16f4iter.SubnetAvailabilityZone.Name
		f16f4elem.SubnetAvailabilityZone = f16f4elemf0
		f16f4elem.SubnetIdentifier = f16f4iter.SubnetIdentifier
		f16f4elemf2 := &svcapitypes.Outpost{}
		f16f4elemf2.ARN = f16f4iter.SubnetOutpost.Arn
		f16f4elem.SubnetOutpost = f16f4elemf2
		f16f4elem.SubnetStatus = f16f4iter.SubnetStatus
		f16f4 = append(f16f4, f16f4elem)
	}
	f16.Subnets = f16f4
	f16.VPCID = resp.DBInstance.DBSubnetGroup.VpcId
	ko.Status.DBSubnetGroup = f16
	ko.Status.DBInstancePort = resp.DBInstance.DbInstancePort
	ko.Status.DBIResourceID = resp.DBInstance.DbiResourceId
	f20 := []*svcapitypes.DomainMembership{}
	for _, f20iter := range resp.DBInstance.DomainMemberships {
		f20elem := &svcapitypes.DomainMembership{}
		f20elem.Domain = f20iter.Domain
		f20elem.FQDN = f20iter.FQDN
		f20elem.IAMRoleName = f20iter.IAMRoleName
		f20elem.Status = f20iter.Status
		f20 = append(f20, f20elem)
	}
	ko.Status.DomainMemberships = f20
	f21 := []*string{}
	for _, f21iter := range resp.DBInstance.EnabledCloudwatchLogsExports {
		var f21elem string
		f21elem = *f21iter
		f21 = append(f21, &f21elem)
	}
	ko.Status.EnabledCloudwatchLogsExports = f21
	f22 := &svcapitypes.Endpoint{}
	f22.Address = resp.DBInstance.Endpoint.Address
	f22.HostedZoneID = resp.DBInstance.Endpoint.HostedZoneId
	f22.Port = resp.DBInstance.Endpoint.Port
	ko.Status.Endpoint = f22
	ko.Status.Engine = resp.DBInstance.Engine
	ko.Status.EngineVersion = resp.DBInstance.EngineVersion
	ko.Status.EnhancedMonitoringResourceARN = resp.DBInstance.EnhancedMonitoringResourceArn
	ko.Status.IAMDatabaseAuthenticationEnabled = resp.DBInstance.IAMDatabaseAuthenticationEnabled
	ko.Status.InstanceCreateTime = &metav1.Time{*resp.DBInstance.InstanceCreateTime}
	ko.Status.LatestRestorableTime = &metav1.Time{*resp.DBInstance.LatestRestorableTime}
	ko.Status.LicenseModel = resp.DBInstance.LicenseModel
	f32 := &svcapitypes.Endpoint{}
	f32.Address = resp.DBInstance.ListenerEndpoint.Address
	f32.HostedZoneID = resp.DBInstance.ListenerEndpoint.HostedZoneId
	f32.Port = resp.DBInstance.ListenerEndpoint.Port
	ko.Status.ListenerEndpoint = f32
	ko.Status.MasterUsername = resp.DBInstance.MasterUsername
	ko.Status.MaxAllocatedStorage = resp.DBInstance.MaxAllocatedStorage
	f38 := []*svcapitypes.OptionGroupMembership{}
	for _, f38iter := range resp.DBInstance.OptionGroupMemberships {
		f38elem := &svcapitypes.OptionGroupMembership{}
		f38elem.OptionGroupName = f38iter.OptionGroupName
		f38elem.Status = f38iter.Status
		f38 = append(f38, f38elem)
	}
	ko.Status.OptionGroupMemberships = f38
	f39 := &svcapitypes.PendingModifiedValues{}
	f39.AllocatedStorage = resp.DBInstance.PendingModifiedValues.AllocatedStorage
	f39.BackupRetentionPeriod = resp.DBInstance.PendingModifiedValues.BackupRetentionPeriod
	f39.CACertificateIdentifier = resp.DBInstance.PendingModifiedValues.CACertificateIdentifier
	f39.DBInstanceClass = resp.DBInstance.PendingModifiedValues.DBInstanceClass
	f39.DBInstanceIdentifier = resp.DBInstance.PendingModifiedValues.DBInstanceIdentifier
	f39.DBSubnetGroupName = resp.DBInstance.PendingModifiedValues.DBSubnetGroupName
	f39.EngineVersion = resp.DBInstance.PendingModifiedValues.EngineVersion
	f39.IOPS = resp.DBInstance.PendingModifiedValues.Iops
	f39.LicenseModel = resp.DBInstance.PendingModifiedValues.LicenseModel
	f39.MasterUserPassword = resp.DBInstance.PendingModifiedValues.MasterUserPassword
	f39.MultiAZ = resp.DBInstance.PendingModifiedValues.MultiAZ
	f39f11 := &svcapitypes.PendingCloudwatchLogsExports{}
	f39f11f0 := []*string{}
	for _, f39f11f0iter := range resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable {
		var f39f11f0elem string
		f39f11f0elem = *f39f11f0iter
		f39f11f0 = append(f39f11f0, &f39f11f0elem)
	}
	f39f11.LogTypesToDisable = f39f11f0
	f39f11f1 := []*string{}
	for _, f39f11f1iter := range resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable {
		var f39f11f1elem string
		f39f11f1elem = *f39f11f1iter
		f39f11f1 = append(f39f11f1, &f39f11f1elem)
	}
	f39f11.LogTypesToEnable = f39f11f1
	f39.PendingCloudwatchLogsExports = f39f11
	f39.Port = resp.DBInstance.PendingModifiedValues.Port
	f39f13 := []*svcapitypes.ProcessorFeature{}
	for _, f39f13iter := range resp.DBInstance.PendingModifiedValues.ProcessorFeatures {
		f39f13elem := &svcapitypes.ProcessorFeature{}
		f39f13elem.Name = f39f13iter.Name
		f39f13elem.Value = f39f13iter.Value
		f39f13 = append(f39f13, f39f13elem)
	}
	f39.ProcessorFeatures = f39f13
	f39.StorageType = resp.DBInstance.PendingModifiedValues.StorageType
	ko.Status.PendingModifiedValues = f39
	ko.Status.PerformanceInsightsEnabled = resp.DBInstance.PerformanceInsightsEnabled
	ko.Status.PreferredBackupWindow = resp.DBInstance.PreferredBackupWindow
	ko.Status.PreferredMaintenanceWindow = resp.DBInstance.PreferredMaintenanceWindow
	ko.Status.PromotionTier = resp.DBInstance.PromotionTier
	f48 := []*string{}
	for _, f48iter := range resp.DBInstance.ReadReplicaDBClusterIdentifiers {
		var f48elem string
		f48elem = *f48iter
		f48 = append(f48, &f48elem)
	}
	ko.Status.ReadReplicaDBClusterIdentifiers = f48
	f49 := []*string{}
	for _, f49iter := range resp.DBInstance.ReadReplicaDBInstanceIdentifiers {
		var f49elem string
		f49elem = *f49iter
		f49 = append(f49, &f49elem)
	}
	ko.Status.ReadReplicaDBInstanceIdentifiers = f49
	ko.Status.ReadReplicaSourceDBInstanceIdentifier = resp.DBInstance.ReadReplicaSourceDBInstanceIdentifier
	ko.Status.SecondaryAvailabilityZone = resp.DBInstance.SecondaryAvailabilityZone
	f52 := []*svcapitypes.DBInstanceStatusInfo{}
	for _, f52iter := range resp.DBInstance.StatusInfos {
		f52elem := &svcapitypes.DBInstanceStatusInfo{}
		f52elem.Message = f52iter.Message
		f52elem.Normal = f52iter.Normal
		f52elem.Status = f52iter.Status
		f52elem.StatusType = f52iter.StatusType
		f52 = append(f52, f52elem)
	}
	ko.Status.StatusInfos = f52
	ko.Status.StorageEncrypted = resp.DBInstance.StorageEncrypted
	ko.Status.TDECredentialARN = resp.DBInstance.TdeCredentialArn
	ko.Status.Timezone = resp.DBInstance.Timezone
	f57 := []*svcapitypes.VpcSecurityGroupMembership{}
	for _, f57iter := range resp.DBInstance.VpcSecurityGroups {
		f57elem := &svcapitypes.VpcSecurityGroupMembership{}
		f57elem.Status = f57iter.Status
		f57elem.VPCSecurityGroupID = f57iter.VpcSecurityGroupId
		f57 = append(f57, f57elem)
	}
	ko.Status.VPCSecurityGroups = f57

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	r *resource,
) (*svcsdk.CreateDBInstanceReadReplicaInput, error) {
	res := &svcsdk.CreateDBInstanceReadReplicaInput{}

	res.SetAutoMinorVersionUpgrade(*r.ko.Spec.AutoMinorVersionUpgrade)
	res.SetAvailabilityZone(*r.ko.Spec.AvailabilityZone)
	res.SetCopyTagsToSnapshot(*r.ko.Spec.CopyTagsToSnapshot)
	res.SetDBInstanceClass(*r.ko.Spec.DBInstanceClass)
	res.SetDBInstanceIdentifier(*r.ko.Spec.DBInstanceIdentifier)
	res.SetDBParameterGroupName(*r.ko.Spec.DBParameterGroupName)
	res.SetDBSubnetGroupName(*r.ko.Spec.DBSubnetGroupName)
	res.SetDeletionProtection(*r.ko.Spec.DeletionProtection)
	res.SetDestinationRegion(*r.ko.Spec.DestinationRegion)
	res.SetDomain(*r.ko.Spec.Domain)
	res.SetDomainIAMRoleName(*r.ko.Spec.DomainIAMRoleName)
	f11 := []*string{}
	for _, f11iter := range r.ko.Spec.EnableCloudwatchLogsExports {
		var f11elem string
		f11elem = *f11iter
		f11 = append(f11, &f11elem)
	}
	res.SetEnableCloudwatchLogsExports(f11)
	res.SetEnableIAMDatabaseAuthentication(*r.ko.Spec.EnableIAMDatabaseAuthentication)
	res.SetEnablePerformanceInsights(*r.ko.Spec.EnablePerformanceInsights)
	res.SetIops(*r.ko.Spec.IOPS)
	res.SetKmsKeyId(*r.ko.Spec.KMSKeyID)
	res.SetMonitoringInterval(*r.ko.Spec.MonitoringInterval)
	res.SetMonitoringRoleArn(*r.ko.Spec.MonitoringRoleARN)
	res.SetMultiAZ(*r.ko.Spec.MultiAZ)
	res.SetOptionGroupName(*r.ko.Spec.OptionGroupName)
	res.SetPerformanceInsightsKMSKeyId(*r.ko.Spec.PerformanceInsightsKMSKeyID)
	res.SetPerformanceInsightsRetentionPeriod(*r.ko.Spec.PerformanceInsightsRetentionPeriod)
	res.SetPort(*r.ko.Spec.Port)
	res.SetPreSignedUrl(*r.ko.Spec.PreSignedURL)
	f24 := []*svcsdk.ProcessorFeature{}
	for _, f24iter := range r.ko.Spec.ProcessorFeatures {
		f24elem := &svcsdk.ProcessorFeature{}
		f24elem.SetName(*f24iter.Name)
		f24elem.SetValue(*f24iter.Value)
		f24 = append(f24, f24elem)
	}
	res.SetProcessorFeatures(f24)
	res.SetPubliclyAccessible(*r.ko.Spec.PubliclyAccessible)
	res.SetSourceDBInstanceIdentifier(*r.ko.Spec.SourceDBInstanceIdentifier)
	res.SetSourceRegion(*r.ko.Spec.SourceRegion)
	res.SetStorageType(*r.ko.Spec.StorageType)
	f29 := []*svcsdk.Tag{}
	for _, f29iter := range r.ko.Spec.Tags {
		f29elem := &svcsdk.Tag{}
		f29elem.SetKey(*f29iter.Key)
		f29elem.SetValue(*f29iter.Value)
		f29 = append(f29, f29elem)
	}
	res.SetTags(f29)
	res.SetUseDefaultProcessorFeatures(*r.ko.Spec.UseDefaultProcessorFeatures)
	f31 := []*string{}
	for _, f31iter := range r.ko.Spec.VPCSecurityGroupIDs {
		var f31elem string
		f31elem = *f31iter
		f31 = append(f31, &f31elem)
	}
	res.SetVpcSecurityGroupIds(f31)

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {
	// TODO(jaypipes): Figure this out...
	return nil

}

