// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package db_cluster_snapshot

import (
	"context"

	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	ackerr "github.com/aws/aws-controllers-k8s/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/rds"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws/aws-controllers-k8s/services/rds/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = &svcsdk.RDS{}
	_ = &svcapitypes.DBClusterSnapshot{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// TODO(jaypipes): Map out the ReadMany codepath

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()
	return &resource{ko}, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateDBClusterSnapshotWithContext(ctx, input)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	ko.Status.AllocatedStorage = resp.DBClusterSnapshot.AllocatedStorage
	f1 := []*string{}
	for _, f1iter := range resp.DBClusterSnapshot.AvailabilityZones {
		var f1elem string
		f1elem = *f1iter
		f1 = append(f1, &f1elem)
	}
	ko.Status.AvailabilityZones = f1
	ko.Status.ClusterCreateTime = &metav1.Time{*resp.DBClusterSnapshot.ClusterCreateTime}
	ko.Status.Engine = resp.DBClusterSnapshot.Engine
	ko.Status.EngineVersion = resp.DBClusterSnapshot.EngineVersion
	ko.Status.IAMDatabaseAuthenticationEnabled = resp.DBClusterSnapshot.IAMDatabaseAuthenticationEnabled
	ko.Status.KMSKeyID = resp.DBClusterSnapshot.KmsKeyId
	ko.Status.LicenseModel = resp.DBClusterSnapshot.LicenseModel
	ko.Status.MasterUsername = resp.DBClusterSnapshot.MasterUsername
	ko.Status.PercentProgress = resp.DBClusterSnapshot.PercentProgress
	ko.Status.Port = resp.DBClusterSnapshot.Port
	ko.Status.SnapshotCreateTime = &metav1.Time{*resp.DBClusterSnapshot.SnapshotCreateTime}
	ko.Status.SnapshotType = resp.DBClusterSnapshot.SnapshotType
	ko.Status.SourceDBClusterSnapshotARN = resp.DBClusterSnapshot.SourceDBClusterSnapshotArn
	ko.Status.Status = resp.DBClusterSnapshot.Status
	ko.Status.StorageEncrypted = resp.DBClusterSnapshot.StorageEncrypted
	ko.Status.VPCID = resp.DBClusterSnapshot.VpcId

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	r *resource,
) (*svcsdk.CreateDBClusterSnapshotInput, error) {
	res := &svcsdk.CreateDBClusterSnapshotInput{}

	res.SetDBClusterIdentifier(*r.ko.Spec.DBClusterIdentifier)
	res.SetDBClusterSnapshotIdentifier(*r.ko.Spec.DBClusterSnapshotIdentifier)
	f2 := []*svcsdk.Tag{}
	for _, f2iter := range r.ko.Spec.Tags {
		f2elem := &svcsdk.Tag{}
		f2elem.SetKey(*f2iter.Key)
		f2elem.SetValue(*f2iter.Value)
		f2 = append(f2, f2elem)
	}
	res.SetTags(f2)

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, respErr := rm.sdkapi.DeleteDBClusterSnapshotWithContext(ctx, input)
	return respErr
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteDBClusterSnapshotInput, error) {
	res := &svcsdk.DeleteDBClusterSnapshotInput{}

	res.SetDBClusterSnapshotIdentifier(*r.ko.Spec.DBClusterSnapshotIdentifier)

	return res, nil
}