
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-controller-role
rules:
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - customavailabilityzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - customavailabilityzones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusterendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusterendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusterparametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusterparametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclustersnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclustersnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstancereadreplicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstancereadreplicas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbparametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbparametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsecuritygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsecuritygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsubnetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsubnetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - eventsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - eventsubscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - globalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - globalclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - optiongroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - optiongroups/status
  verbs:
  - get
  - patch
  - update
