// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DBClusterEndpointSpec defines the desired state of DBClusterEndpoint
type DBClusterEndpointSpec struct {
	DBClusterEndpointIdentifier *string `json:"dbClusterEndpointIdentifier,omitempty"`
	DBClusterIdentifier *string `json:"dbClusterIdentifier,omitempty"`
	EndpointType *string `json:"endpointType,omitempty"`
	ExcludedMembers []*string `json:"excludedMembers,omitempty"`
	StaticMembers []*string `json:"staticMembers,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}

// DBClusterEndpointStatus defines the observed state of DBClusterEndpoint
type DBClusterEndpointStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	CustomEndpointType *string `json:"customEndpointType,omitempty"`
	DBClusterEndpointResourceIdentifier *string `json:"dbClusterEndpointResourceIdentifier,omitempty"`
	Endpoint *string `json:"endpoint,omitempty"`
	Status *string `json:"status,omitempty"`
}

// DBClusterEndpoint is the Schema for the DBClusterEndpoints API
// +kubebuilder:object:root=true
type DBClusterEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   DBClusterEndpointSpec   `json:"spec,omitempty"`
	Status DBClusterEndpointStatus `json:"status,omitempty"`
}

// DBClusterEndpointList contains a list of DBClusterEndpoint
// +kubebuilder:object:root=true
type DBClusterEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []DBClusterEndpoint `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DBClusterEndpoint{}, &DBClusterEndpointList{})
}